### ISSUE TITLE
Some svgs have white backgrounds

### ISSUE THREAD

**Issue by willgearty** [keesey/phylopic#14]
I've discovered that some phylopic svgs have white background layers, e.g.:
https://images.phylopic.org/images/eedde61f-3402-4f7c-9350-49b74f5e1dba/vector.svg
https://images.phylopic.org/images/2de1c95c-7e1f-429b-9c08-17f0a27d176f/vector.svg

This isn't normally an issue for general use, but when you try to programmatically change the color of the silhouette (e.g., in rphylopic), there isn't an easy way to identify which layers are the background and which layers are the foreground, so you end up coloring all of them, which makes a lovely colored rectangle.

In my experience most phylopic svgs seem to have no background layers, so this seems like an abnormality, but I don't know how to programmatically find all of the uuids for phylopics that have svgs with backgrounds. Let me know if there's any way I can help further.

**Comment by keesey** [comment]
This is essentially the same core problem as https://github.com/keesey/phylopic/issues/15
SVGs files are not modified during submission -- they're just whatever the contributor submitted. I don't have a good solution for this now, but would like to think about it.

**Comment by keesey** [comment]
This can be handled by the solution for #15.
