### ISSUE TITLE
SVGs with superfluous paths

### ISSUE THREAD

**Issue by willgearty** [keesey/phylopic#15]
I was browsing through various SVGs, when I noticed that this one was significantly larger than most other PhyloPic svgs:
https://images.phylopic.org/images/347bc4ab-c1e0-4313-9ea1-939c2ad71232/vector.svg. This fungus one, which (to the untrained eye) just looks like 2 ovals, is ~193 KB, while one for a more complicated (polygon-wise) [macaque is only 59KB](https://images.phylopic.org/images/eedde61f-3402-4f7c-9350-49b74f5e1dba/vector.svg) and [one for a chicken is even smaller at 13 KB](https://images.phylopic.org/images/2de1c95c-7e1f-429b-9c08-17f0a27d176f/vector.svg).

Upon further investigation, I noticed that the fungus SVG has many seemingly superfluous paths which are transparent. When those paths are removed, the SVG reduces in size to only 50 KB, much more in line with the sizes of other PhyloPic SVGs. Perhaps this is related to the auto-svg tool on PhyloPic.org?

**Comment by keesey** [comment]
No, this was submitted before automatic vectorization was added. It's the SVG files as submitted. And stuff like this can still happen on new submissions, if submitted as SVG. I have not thought up a good solution to this, but I would love to "sanitize" submitted vector images, similar what's done with the raster images.

**Comment by keesey** [comment]
Another idea would be to offer a "sanitized" version *and* the original, separately, That might be better. Wouldn't need a change to the API, since `sourceFile` and `vectorFile` are already available. (Currently they indicate the same file, if uploaded as an SVG.)

**Comment by willgearty** [comment]
I like the idea of a "sanitized" version

**Comment by keesey** [comment]
Yeah, that seems like the best option. The real question is, what's the best way to "sanitize"? Maybe "normalize" is a better term? The "revectorization" idea is the best I've got, but I don't love it.

**Comment by keesey** [comment]
Maybe I'm okay with it....
Can always change it to something else later.

**Comment by willgearty** [comment]
Another example of a bad SVG: https://www.phylopic.org/images/3d8acaf6-4355-491e-8e86-4a411b53b98b/sus-scrofa
It's actually just a png with an SVG clip path on top.

**Comment by keesey** [comment]
Thanks, I'll fix that one manually in the next build.

**Comment by willgearty** [comment]
Thanks!

**Comment by keesey** [comment]
Opened a PR for this: https://github.com/keesey/phylopic/pull/28

(It actually should be working in production already, but this PR is needed to keep it working going forward, as well as to make some UI and verbiage adjustments.)

**Comment by willgearty** [comment]
Excellent!
