### ISSUE TITLE
Cervus nippon Silhouette - Broken Link

### ISSUE THREAD

**Issue by foofoobun** [keesey/phylopic#21]
There appears to be one available silhouette for _Cervus nippon_, but the path linked to this silhouette (https://www.phylopic.org/images/dbf886d8-42f3-4d7b-8a93-45d4b3e72f9c/cervus-nippon) leads to an error page (photo attached). Is this silhouette no longer available? Thanks in advance!

![cervus-nippon-error](https://user-images.githubusercontent.com/104316732/236446858-af89c546-714a-4419-aaec-bad085370ae7.JPG)

**Comment by keesey** [comment]
Works now, but I have noticed something like this one other time, when I was unable to access the [page for _Anura_ ](https://www.phylopic.org/nodes/1ccf2477-1681-4a57-b4a8-45a479f33626/anura-silhouettes). I think there might be a very infrequent issue with API errors (timeouts) getting cached in the website layer. Hard to troubleshoot, given how rare it is, but I'll keep an eye out for it.

**Comment by keesey** [comment]
This is the same as this issue, I'm pretty certain: https://github.com/keesey/phylopic/issues/23
