### ISSUE TITLE
Image misclassified

### ISSUE THREAD

**Issue by MABroussard** [keesey/phylopic#26]
Not certain if this is the correct place to report misclassified images, but here goes:

https://www.phylopic.org/images/788379fa-8762-4dbd-b486-8632db474b58/monopis-crocicapitella
Is incorrectly listed as a moth when it is a bird.

The following image has been uploaded as both a generic and specific silhouette
https://www.phylopic.org/images/cc3278ac-31b9-44f1-bf93-5bcd5f45b2ff/scaptotrigona
https://www.phylopic.org/images/c516108a-f247-41e9-9252-4e1cc405eace/scaptotrigona-polysticta

**Comment by keesey** [comment]
This is a great place to report them.

The first one I think is intended to illustrated the moth in its habitat, which happens to be an occupied bird nest. I'll check with the contributor. (Unfortunately PhyloPic does not allow for multiple species assignments at proest.)

There is a slight difference in the second and third images, a band of stripes that only appears in the species.

**Comment by keesey** [comment]
Never mind, you are correct, that *is* supposed to be a bird (_Turdus rufiventris_). I'm not sure how it got misassigned. Fixing in the next build....

**Comment by keesey** [comment]
Fixed now, thanks for reporting it.
