### ISSUE TITLE
Image warped/cropped wrong

### ISSUE THREAD

**Issue by sarahfrail** [keesey/phylopic#27]
Hello, thanks so much for this wonderful resource. I've recently been uploading some diatoms illustrations to the site. 

I noticed that a few of my accepted submissions have some warping/cropping issues. 

1) [Thalassiosira pseudonana](https://www.phylopic.org/images/ebff2e9f-3091-4ad6-a7b2-f39a77d3a960/thalassiosira-pseudonana) seems to have gotten warped, a center part of the drawing has been shrunk and shifted over from my original illustration. 

2) When creating my illustrations in inkscape, I left some real microscopy images of diatoms outside of the page. These did not show up in the preview when uploading, but seem to show up on the actual organism pages themselves (see [seminavis robusta](https://www.phylopic.org/images/737ff470-5057-4dd2-9759-93a65558c11a/seminavis-robusta)) 

Is there any way to retract or fix the images? I'm happy to remove images at the margins and re-upload, but I have no idea how to fix the issue with T. pseudonana

**Comment by keesey** [comment]
Reuploaded the first one after editing in Illustrator. Seems fine now.

**Comment by keesey** [comment]
The second one is fixed now, too.

**Comment by keesey** [comment]
I forgot to record what I did for the first one, but for the second one I copied the relevant portion over to an entirely new file.
