### ISSUE TITLE
Links to https://training.paleobiodb.org/ should go to https://paleobiodb.org/

### ISSUE THREAD

**Issue by mmcclenn** [keesey/phylopic#31]
There are quite a few links on the documentation pages that refer to https://training.paleobiodb.org/. That server is intended for training purposes (as the name suggests) and its database does not contain all of the latest data. All of these links need to be changed so that they point to our main server at https://paleobiodb.org/, which provides the same functionality and executes queries against the latest version of the database.

**Comment by keesey** [comment]
Thanks for spotting that! It's fixed now.

**Comment by keesey** [comment]
Thanks for spotting that! It's fixed now.

**Comment by mmcclenn** [comment]
Thank you for taking care of this so quickly!
