### ISSUE TITLE
Query API v2 for images modified within a range

### ISSUE THREAD

**Issue by AetherUnbound** [keesey/phylopic#5]
Hello! I'm one of the maintainers of [Openverse](https://github.com/WordPress/openverse), a search engine for openly licensed media on the web. Phylopic is one of the sources of CC images we ingest regularly, and unfortunately our ingestion broke with the move to the API v2.

In our exploration regarding what it would take to migrate (issue here: https://github.com/WordPress/openverse-catalog/issues/998), it doesn't look like there's a way to query images which were _modified_ within a certain date range. The previous URLs looked something like http://phylopic.org/api/a/image/list/modified/2023-02-12/2023-02-13 (and documentation to the method in question was here http://phylopic.org/api/#method-image-time-range, although that link no longer works after the v2 migration).

I may be misinterpreting what's possible with the new API, and forgive me if this is the wrong place to ask, but - is it possible using v2 to query images by modification date? It seems like that information [might be captured on the Image model itself](https://github.com/keesey/phylopic/blob/bbfd32b27e586cf4c9f62cf8aa1f90d4c115205e/packages/source-models/src/types/Image.ts#L7), but I wasn't able to find a field reference for it in the API (I'm also no TypeScript aficionado :sweat_smile:). We'd love to continue updating our index in this fashion if it's possible to do so!

**Comment by keesey** [comment]
The data has been fixed up for legacy images.

Here is a proposal for API changes to add new filters. Does this look like it would address the issue? https://github.com/keesey/phylopic/blob/feature/date-filters/apps/api-docs/public/v2/openapi.yaml

**Comment by AetherUnbound** [comment]
Thanks for getting back to us @keesey! The spec you outlined in #8 looks like exactly what we would ideally use 😄 Let us know if there's any way we can help or test out the new endpoints!

**Comment by keesey** [comment]
Cool, I'll let you know when it's done. (Might not be for a little while.)

**Comment by keesey** [comment]
I lied, I finished it already.
Documentation: http://api-docs.phylopic.org/v2/
Sample URL: https://api.phylopic.org/images?filter_modified_after=2023-01-01T00:00:00.000Z
